import './search-bar.js';
import './quotes.js';
import './display_quote.js';
import './display_citydate.js';
import './display_currentdate.js';
import './today.js';
import './five-days.js';
import './hourly.js';
import './background.js';
//import "./chart.js"
